on:
  push:
    branches:
      - "main"
jobs:
  day-08:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: ./mvnw -q -Dtest=Day08Test test