on:
  push:
    branches:
      - "main"
jobs:
  day-23:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'
      - run: ./mvnw -q -Dtest=Day23Test test